### ISSUE TITLE
how to train custom data

### ISSUE THREAD

**Issue by cnjhh** [WongKinYiu/yolov9#30]

**Comment by WongKinYiu** [comment]
Make sure your dataset has same format as provided format for coco dataset.
Modify the coco.yaml and yolov9.yaml to fit your dataset.
Then you can train your custom data.

**Comment by SkalskiP** [comment]
Hi, @cnjhh and @WongKinYiu. I spent some time assembling this [notebook](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov9-object-detection-on-custom-dataset.ipynb). It shows how to:
- Run inference with a pre-trained model
- **Fine-tune models on custom dataset**
- Evaluate fine-tuned model
- Run inference with fine-tuned model

@WongKinYiu I'd love to add this link to `README.md`, but I understand if you prefare not to. :)

**Comment by WongKinYiu** [comment]
Done.

**Comment by SkalskiP** [comment]
@WongKinYiu Thank you! 🙏🏻 I'm super honored. Maybe we could include a badge at the top of the README?

[![Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/zero-shot-object-detection-with-yolo-world.ipynb)

**Comment by berengueradrian** [comment]
Hi @WongKinYiu @SkalskiP, is there any way to perform fine-tuning on the model using a custom dataset with different structure than the one used in the Colab(YOLO structure)? 

I want to use it for a dataset with a different structure and I would like to know if you have some hints on how to carry this out. I have a lot of data and it is not efficient for me to transform that bunch of data into the YOLO structure, I would like to have a 'general' approach in order to be able to train it with different dataset structures. My structure is in this case is:

```
├── src
│   ├── images
│   │   ├── <class_directory>/<image>.jpg
│   ├── bounding_boxes.txt
│   ├── classes.txt
│   ├── image_class_labels.txt
│   ├── images.txt
│   ├── train_test_splits.txt
```

Thanks in advance.

**Comment by rmukh** [comment]
@berengueradrian I guess it is not possible to create a 'general approach' that supports all possible user's dataset structures. That's why we have different data formats (COCO, YOLO, etc). The code can be refactored to expect the user's dataloader, but it would take some time to properly refactor. So, I guess you can use your own custom dataloader and insert it here https://github.com/WongKinYiu/yolov9/blob/380284cb66817e9ffa30a80cad4c1b110897b2fb/train.py#L177
Just make sure your dataloader outputs the data in the expected format.

**Comment by berengueradrian** [comment]
All right, thanks for the info!

**Comment by Emil-Ohanesyan** [comment]
hello there. I wanted to know that this model is already trained? or I need to train it myself?

**Comment by fazrigading** [comment]
> hello there. I wanted to know that this model is already trained? or I need to train it myself?

The model already trained on COCO dataset resulting a model weight. You can use the weight listed on the repo to train with your model (called transfer learning).

**Comment by Emil-Ohanesyan** [comment]
thank you so much for your answer.  I just used .pt file to just finetune
it. and one question that I got is that how many epochs do you think I need
to train for my fine tune phase?

**Comment by fazrigading** [comment]
> thank you so much for your answer.  I just used .pt file to just finetune
> it. and one question that I got is that how many epochs do you think I need
> to train for my fine tune phase?
> […](#)

Apologize for the very late reply.
I personally use 25-50 epochs if my custom dataset has any class included in COCO dataset. If my custom dataset object classes not available in COCO dataset, use 100-300 epochs. 100 epochs is the best option in my opinion.

**Comment by Emil-Ohanesyan** [comment]
thank you so much for your help. can I have your email please?

**Comment by fazrigading** [comment]
> thank you so much for your help. can I have your email please?

Sure, please check my GitHub profile. @Emil-Ohanesyan
