### ISSUE TITLE
Is incremental training possible?

### ISSUE THREAD

**Issue by shubzk** [WongKinYiu/yolov9#335]
I have a dataset with 5000 images containing 21 classes. However, I get new 500 images every 2 days with the same classes. Can I use the previous 'best.pt' weight file to only train on the new data and still retain all the information learned from previous trainings? 
NOTE: The classes remain the same.

**Comment by Youho99** [comment]
Check issue #323

**Comment by levipereira** [comment]
If the images are significantly different from the original dataset, the training will update the all weights for the backbone layers to extract features, it's recommended to wait until you accumulate a week's worth of images and train everything at once. This is because every time you train the backbone, the new images influence the existing weights, potentially yielding poor results in each epoch until the optimal weights are found.

However, if the images don't represent significant changes in the classes, then you can train just the HEAD, which consists freeze backbone weights and training only final layers of the model. This process is quicker, allowing you to train daily.
