### ISSUE TITLE
I wonder what the latency of the model is.

### ISSUE THREAD

**Issue by visionNoob** [WongKinYiu/yolov9#65]
Thank you for suggesting a good method for real time object-detection. 
I have a question 
I just looking at the papers in the arXiv but there's no comparison of latency but # params and FLOPs.
Is it because you are still preparing to implement an optimized version (like cuda or something)? 
I wonder what the actual latency is like.
Thank you!

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/issues/178#issue-2170971202

The main reason we do not show latency is due to different exporting method and even different version of tools will effect too much on latency. 

You could take a look yolov6 v3.0 arxiv.
1. T4 TRT 7: YOLOv7 10% faster than YOLOv6 v3.0
2. T4 TRT 8: YOLOv7 20% faster than YOLOv6 v3.0
3. V100 : YOLOv7 more than 30% faster than YOLOv6 v3.0

Many paper show their latency without provide detail information, so we can not verify if the reported latency are fair comparison.
